FROM busybox
ADD ./export/node_modules /usr/local/node/lib/node_modules
RUN [ "sh", "-c", "touch /$(date '+%Y-%m-%d_%H:%M:%S')" ]
RUN mkdir -p /usr/local/node/lib/node_modules
VOLUME /usr/local/node/lib/node_modules